name: workspace_sandbox
description: >
  Cross-platform sandboxed workspace manager for running shell commands
  with streaming output and native isolation.
version: 0.1.1

repository: https://github.com/deskhand-software/workspace_sandbox
issue_tracker: https://github.com/deskhand-software/workspace_sandbox/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  windows:
  linux:

dependencies:
  ffi: ^2.1.3
  path: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.26.0
